import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={`${styles.mainNav}`}>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
            <Link href="/blog">Blog</Link>
          </li>
          <li>
            <Link href="/contact">Contact</Link>
          </li>
        </ul>
      </nav>

      <div className={styles.title}>
        <h1>Hunting Coder</h1>
      </div>

      <div className={styles.subtitle}>
        A blog for hunting coders by hunting coder
      </div>

      <div className={styles.blogs}>
        <h2>Popular Blogs:</h2>
        <div className={styles.blogItems}>
          <h3>How to learn Javascript in 2022?</h3>
          <p>{`JavaScript is a versatile and widely used programming language primarily known for its role in web development.`}</p>
        </div>

        <div className={styles.blogItems}>
          <h3>How to learn Javascript in 2022?</h3>
          <p>{`JavaScript is a versatile and widely used programming language primarily known for its role in web development.`}</p>
        </div>

        <div className={styles.blogItems}>
          <h3>How to learn Javascript in 2022?</h3>
          <p>{`JavaScript is a versatile and widely used programming language primarily known for its role in web development.`}</p>
        </div>
      </div>
    </>
  );
}
